root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/wheel ./cmd/worker"
entrypoint = "tmp/wheel"
delay = 1000
exclude_dir = ["tmp", "bin"]
exclude_regex = ["_test\\.go$"]
kill_delay = 500

[misc]
clean_on_exit = true
