// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/apikey/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Create a new API key",
                "parameters": [
                    {
                        "description": "API key config: name, expireAt, maxCost, supportedModels",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: APIKey}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/apikey/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Delete an API key",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "API Key ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/apikey/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "List all API keys",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {apiKeys: []APIKey}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/apikey/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Update an API key",
                "parameters": [
                    {
                        "description": "Partial API key fields to update (id required)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Create a new channel",
                "parameters": [
                    {
                        "description": "Channel configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kunish_wheel_apps_worker_internal_types.ChannelCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: Channel}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Delete a channel",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Channel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/enable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Enable or disable a channel",
                "parameters": [
                    {
                        "description": "Channel ID and enabled state",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kunish_wheel_apps_worker_internal_types.ChannelEnableRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/fetch-model": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Fetch models from an existing channel",
                "parameters": [
                    {
                        "description": "Channel ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.fetchModelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: {models: []string}}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/fetch-model-preview": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Preview models from channel credentials (without saving)",
                "parameters": [
                    {
                        "description": "Channel type, base URL, and API key",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.fetchModelPreviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: {models: []string}}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/last-sync-time": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Get last model sync timestamp",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {lastSyncTime: int}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "List all channels",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {channels: []Channel}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Sync models from all auto-sync channels",
                "responses": {
                    "200": {
                        "description": "{success: true, data: SyncResult}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Update channel configuration",
                "parameters": [
                    {
                        "description": "Partial channel fields to update (id required)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/group/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Create a new routing group",
                "parameters": [
                    {
                        "description": "Group configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kunish_wheel_apps_worker_internal_types.GroupCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: Group}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/group/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Delete a routing group",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Group ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/group/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "List all routing groups",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {groups: []Group}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/group/model-list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "List all models available across channels",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {models: []string}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/group/reorder": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Reorder routing groups",
                "parameters": [
                    {
                        "description": "Ordered group IDs",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.reorderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/group/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Update group configuration",
                "parameters": [
                    {
                        "description": "Partial group fields to update (id required)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/log/clear": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Clear all relay logs",
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/log/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Delete a relay log",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Log ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/log/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "List relay logs with pagination and filters",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Page size (max 200)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by channel ID",
                        "name": "channelId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by start timestamp",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by end timestamp",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by model name",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (error|success)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: {logs, total, page, pageSize}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/log/replay/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Replay a logged request (not yet implemented)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Log ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "501": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/log/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Get a single relay log by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Log ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: RelayLog}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/model/channel": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "List models grouped by channel",
                "responses": {
                    "200": {
                        "description": "{success: true, data: []object}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/model/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Create a model price entry",
                "parameters": [
                    {
                        "description": "Model name and prices",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: LLMPrice}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "409": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/model/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Delete a model price entry",
                "parameters": [
                    {
                        "description": "Model ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/model/last-update-time": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Get last price sync timestamp",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {lastUpdateTime: string}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/model/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "List all model prices",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {models: []LLMPrice}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/model/metadata": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Get model metadata (provider, logo, etc.)",
                "responses": {
                    "200": {
                        "description": "{success: true, data: map[string]modelMeta}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/model/metadata/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Refresh model metadata from models.dev",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {count: int}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/model/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Update a model price entry",
                "parameters": [
                    {
                        "description": "Model ID and optional fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/model/update-price": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Sync model prices from models.dev",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {synced: int, updated: int}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/setting/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Get all settings",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {settings: map[string]string}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/setting/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Export all data as JSON file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Include relay logs (true|false)",
                        "name": "include_logs",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JSON export file",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/api/v1/setting/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Import data from JSON file or body",
                "parameters": [
                    {
                        "type": "file",
                        "description": "JSON export file",
                        "name": "file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: ImportResult}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/setting/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Update settings",
                "parameters": [
                    {
                        "description": "Settings key-value pairs",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kunish_wheel_apps_worker_internal_types.SettingsUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/apikey": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get per-API-key statistics",
                "responses": {
                    "200": {
                        "description": "{success: true, data: []object}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/channel": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get per-channel statistics",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {channels: []ChannelStatsItem}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/daily": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get daily statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Timezone offset (e.g. +08:00)",
                        "name": "tz",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: []DailyStatsItem}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/global": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get global statistics overview",
                "responses": {
                    "200": {
                        "description": "{success: true, data: GlobalStatsResponse}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/hourly": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get hourly statistics for a date range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYYMMDD)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYYMMDD)",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Timezone offset (e.g. +08:00)",
                        "name": "tz",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: []HourlyStatsItem}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/model": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get per-model statistics",
                "responses": {
                    "200": {
                        "description": "{success: true, data: []ModelStatsItem}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/today": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get today's statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Timezone offset (e.g. +08:00)",
                        "name": "tz",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: DailyStatsItem}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/total": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get all-time total statistics",
                "responses": {
                    "200": {
                        "description": "{success: true, data: DailyStatsItem}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/user/apikey/login": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Get API key info (end-user)",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {id, name, enabled, expireAt, maxCost, totalCost, supportedModels}}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/user/apikey/stats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Get API key usage stats (end-user)",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {id, name, totalCost, maxCost, enabled, expireAt}}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/user/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Change admin password",
                "parameters": [
                    {
                        "description": "Old and new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.changePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/user/change-username": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Change admin username",
                "parameters": [
                    {
                        "description": "New username",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.changeUsernameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Admin login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{success: true, data: {token, expireAt}}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "{success: false, error: string}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/user/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Check authentication status",
                "responses": {
                    "200": {
                        "description": "{success: true, data: {authenticated: true}}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_kunish_wheel_apps_worker_internal_types.BaseUrl": {
            "type": "object",
            "properties": {
                "delay": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_kunish_wheel_apps_worker_internal_types.ChannelCreateRequest": {
            "type": "object",
            "properties": {
                "autoGroup": {
                    "type": "integer"
                },
                "autoSync": {
                    "type": "boolean"
                },
                "baseUrls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kunish_wheel_apps_worker_internal_types.BaseUrl"
                    }
                },
                "customHeader": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kunish_wheel_apps_worker_internal_types.CustomHeader"
                    }
                },
                "customModel": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kunish_wheel_apps_worker_internal_types.ChannelKeyInput"
                    }
                },
                "model": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "paramOverride": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "github_com_kunish_wheel_apps_worker_internal_types.ChannelEnableRequest": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "github_com_kunish_wheel_apps_worker_internal_types.ChannelKeyInput": {
            "type": "object",
            "properties": {
                "channelKey": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "github_com_kunish_wheel_apps_worker_internal_types.CustomHeader": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_kunish_wheel_apps_worker_internal_types.GroupCreateRequest": {
            "type": "object",
            "properties": {
                "firstTokenTimeOut": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kunish_wheel_apps_worker_internal_types.GroupItemInput"
                    }
                },
                "mode": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_kunish_wheel_apps_worker_internal_types.GroupItemInput": {
            "type": "object",
            "properties": {
                "channelId": {
                    "type": "integer"
                },
                "modelName": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "github_com_kunish_wheel_apps_worker_internal_types.SettingsUpdateRequest": {
            "type": "object",
            "properties": {
                "settings": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handler.changePasswordRequest": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "internal_handler.changeUsernameRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handler.fetchModelPreviewRequest": {
            "type": "object",
            "properties": {
                "baseUrl": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.fetchModelRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.loginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handler.reorderRequest": {
            "type": "object",
            "properties": {
                "orderedIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Wheel API",
	Description:      "LLM API Gateway — aggregate providers, manage load balancing, and track usage/costs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
