/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/apikey/create": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a new API key */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description API key config: name, expireAt, maxCost, supportedModels */
      requestBody: {
        content: {
          "application/json": Record<string, never>
        }
      }
      responses: {
        /** @description {success: true, data: APIKey} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/apikey/delete/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete an API key */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description API Key ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/apikey/list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all API keys */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {apiKeys: []APIKey}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/apikey/update": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Update an API key */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Partial API key fields to update (id required) */
      requestBody: {
        content: {
          "application/json": Record<string, never>
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/channel/create": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a new channel */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Channel configuration */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_kunish_wheel_apps_worker_internal_types.ChannelCreateRequest"]
        }
      }
      responses: {
        /** @description {success: true, data: Channel} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/channel/delete/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete a channel */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Channel ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/channel/enable": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Enable or disable a channel */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Channel ID and enabled state */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_kunish_wheel_apps_worker_internal_types.ChannelEnableRequest"]
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/channel/fetch-model": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Fetch models from an existing channel */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Channel ID */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_handler.fetchModelRequest"]
        }
      }
      responses: {
        /** @description {success: true, data: {models: []string}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/channel/fetch-model-preview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Preview models from channel credentials (without saving) */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Channel type, base URL, and API key */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_handler.fetchModelPreviewRequest"]
        }
      }
      responses: {
        /** @description {success: true, data: {models: []string}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/channel/last-sync-time": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get last model sync timestamp */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {lastSyncTime: int}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/channel/list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all channels */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {channels: []Channel}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/channel/sync": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Sync models from all auto-sync channels */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: SyncResult} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/channel/update": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Update channel configuration */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Partial channel fields to update (id required) */
      requestBody: {
        content: {
          "application/json": Record<string, never>
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/group/create": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a new routing group */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Group configuration */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_kunish_wheel_apps_worker_internal_types.GroupCreateRequest"]
        }
      }
      responses: {
        /** @description {success: true, data: Group} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/group/delete/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete a routing group */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Group ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/group/list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all routing groups */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {groups: []Group}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/group/model-list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all models available across channels */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {models: []string}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/group/reorder": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reorder routing groups */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Ordered group IDs */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_handler.reorderRequest"]
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/group/update": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Update group configuration */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Partial group fields to update (id required) */
      requestBody: {
        content: {
          "application/json": Record<string, never>
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/log/clear": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Clear all relay logs */
    delete: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/log/delete/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete a relay log */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Log ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/log/list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List relay logs with pagination and filters */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number
          /** @description Page size (max 200) */
          pageSize?: number
          /** @description Filter by channel ID */
          channelId?: number
          /** @description Filter by start timestamp */
          startTime?: number
          /** @description Filter by end timestamp */
          endTime?: number
          /** @description Filter by model name */
          model?: string
          /** @description Search keyword */
          keyword?: string
          /** @description Filter by status (error|success) */
          status?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {logs, total, page, pageSize}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/log/replay/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Replay a logged request (not yet implemented) */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Log ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        501: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/log/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a single relay log by ID */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Log ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: RelayLog} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/model/channel": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List models grouped by channel */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: []object} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/model/create": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a model price entry */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Model name and prices */
      requestBody: {
        content: {
          "application/json": Record<string, never>
        }
      }
      responses: {
        /** @description {success: true, data: LLMPrice} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/model/delete": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Delete a model price entry */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Model ID */
      requestBody: {
        content: {
          "application/json": Record<string, never>
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/model/last-update-time": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get last price sync timestamp */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {lastUpdateTime: string}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/model/list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all model prices */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {models: []LLMPrice}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/model/metadata": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get model metadata (provider, logo, etc.) */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: map[string]modelMeta} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/model/metadata/refresh": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh model metadata from models.dev */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {count: int}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/model/update": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Update a model price entry */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Model ID and optional fields to update */
      requestBody: {
        content: {
          "application/json": Record<string, never>
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/model/update-price": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Sync model prices from models.dev */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {synced: int, updated: int}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/setting/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all settings */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {settings: map[string]string}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/setting/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Export all data as JSON file */
    get: {
      parameters: {
        query?: {
          /** @description Include relay logs (true|false) */
          include_logs?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description JSON export file */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": string
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/setting/import": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Import data from JSON file or body */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "multipart/form-data": {
            /**
             * Format: binary
             * @description JSON export file
             */
            file?: string
          }
        }
      }
      responses: {
        /** @description {success: true, data: ImportResult} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/setting/update": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Update settings */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Settings key-value pairs */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_kunish_wheel_apps_worker_internal_types.SettingsUpdateRequest"]
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stats/apikey": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get per-API-key statistics */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: []object} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stats/channel": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get per-channel statistics */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {channels: []ChannelStatsItem}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stats/daily": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get daily statistics */
    get: {
      parameters: {
        query?: {
          /** @description Timezone offset (e.g. +08:00) */
          tz?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: []DailyStatsItem} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stats/global": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get global statistics overview */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: GlobalStatsResponse} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stats/hourly": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get hourly statistics for a date range */
    get: {
      parameters: {
        query?: {
          /** @description Start date (YYYYMMDD) */
          start?: string
          /** @description End date (YYYYMMDD) */
          end?: string
          /** @description Timezone offset (e.g. +08:00) */
          tz?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: []HourlyStatsItem} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stats/model": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get per-model statistics */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: []ModelStatsItem} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stats/today": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get today's statistics */
    get: {
      parameters: {
        query?: {
          /** @description Timezone offset (e.g. +08:00) */
          tz?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: DailyStatsItem} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stats/total": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all-time total statistics */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: DailyStatsItem} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/user/apikey/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get API key info (end-user) */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {id, name, enabled, expireAt, maxCost, totalCost, supportedModels}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/user/apikey/stats": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get API key usage stats (end-user) */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {id, name, totalCost, maxCost, enabled, expireAt}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/user/change-password": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Change admin password */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Old and new password */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_handler.changePasswordRequest"]
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/user/change-username": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Change admin username */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description New username */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_handler.changeUsernameRequest"]
        }
      }
      responses: {
        /** @description {success: true} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/user/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Admin login */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Login credentials */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_handler.loginRequest"]
        }
      }
      responses: {
        /** @description {success: true, data: {token, expireAt}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
        /** @description {success: false, error: string} */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/user/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Check authentication status */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description {success: true, data: {authenticated: true}} */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    "github_com_kunish_wheel_apps_worker_internal_types.BaseUrl": {
      delay?: number
      url?: string
    }
    "github_com_kunish_wheel_apps_worker_internal_types.ChannelCreateRequest": {
      autoGroup?: number
      autoSync?: boolean
      baseUrls?: components["schemas"]["github_com_kunish_wheel_apps_worker_internal_types.BaseUrl"][]
      customHeader?: components["schemas"]["github_com_kunish_wheel_apps_worker_internal_types.CustomHeader"][]
      customModel?: string
      enabled?: boolean
      keys?: components["schemas"]["github_com_kunish_wheel_apps_worker_internal_types.ChannelKeyInput"][]
      model?: string[]
      name?: string
      paramOverride?: string
      type?: number
    }
    "github_com_kunish_wheel_apps_worker_internal_types.ChannelEnableRequest": {
      enabled?: boolean
      id?: number
    }
    "github_com_kunish_wheel_apps_worker_internal_types.ChannelKeyInput": {
      channelKey?: string
      remark?: string
    }
    "github_com_kunish_wheel_apps_worker_internal_types.CustomHeader": {
      key?: string
      value?: string
    }
    "github_com_kunish_wheel_apps_worker_internal_types.GroupCreateRequest": {
      firstTokenTimeOut?: number
      items?: components["schemas"]["github_com_kunish_wheel_apps_worker_internal_types.GroupItemInput"][]
      mode?: number
      name?: string
    }
    "github_com_kunish_wheel_apps_worker_internal_types.GroupItemInput": {
      channelId?: number
      modelName?: string
      priority?: number
      weight?: number
    }
    "github_com_kunish_wheel_apps_worker_internal_types.SettingsUpdateRequest": {
      settings?: {
        [key: string]: string
      }
    }
    "internal_handler.changePasswordRequest": {
      newPassword?: string
      oldPassword?: string
    }
    "internal_handler.changeUsernameRequest": {
      username?: string
    }
    "internal_handler.fetchModelPreviewRequest": {
      baseUrl?: string
      key?: string
      type?: number
    }
    "internal_handler.fetchModelRequest": {
      id?: number
    }
    "internal_handler.loginRequest": {
      password?: string
      username?: string
    }
    "internal_handler.reorderRequest": {
      orderedIds?: number[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
